version: "3.8"

services:
  client:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  server:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
